###
GET http://localhost:1337/api/users/9 HTTP/1.1

###
DELETE http://localhost:1337/api/users/162 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpZCI6NiwiaWF0IjoxNTgzNTk1NTE1LCJleHAiOjE2MTUxMzE1MTV9.BJWN4VCoHEpvEG4SKWZeyGCOPvqdqmUZHQol7fwiSyY

###
DELETE http://localhost:1337/api/boards/4 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpZCI6NiwiaWF0IjoxNTgzNTk1NTE1LCJleHAiOjE2MTUxMzE1MTV9.BJWN4VCoHEpvEG4SKWZeyGCOPvqdqmUZHQol7fwiSyY

###
GET http://localhost:1337/api/boards HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpZCI6NiwiaWF0IjoxNTgzNTk1NTE1LCJleHAiOjE2MTUxMzE1MTV9.BJWN4VCoHEpvEG4SKWZeyGCOPvqdqmUZHQol7fwiSyY

###