POST http://localhost:1337/api/users/register/ HTTP/1.1
content-type: application/json

{
    "userName": "UserName2",
    "password": "P@ssw0rd",
    "email": "username2@provider.com",
    "firstName": "FirstName",
    "lastName": "LastName",
    "languagePreference": "en"
}

###

POST http://localhost:1337/api/users/login HTTP/1.1
content-type: application/json

{
    "username": "TestUser2",
    "password": "P@ssw0rd"
}

###

//LOGOUT via AcessToken
DELETE http://localhost:1337/api/users/logout HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVGVzdFVzZXIyIiwiaWQiOjcsImlhdCI6MTU4MjY2ODU4OSwiZXhwIjoxNTgyNjY5NDg5fQ.PklZuN0gyO89WbegyOvmwesYeaAtVy8qEMMoIlHgK60

###

//LOGOUT via RefreshToken
DELETE http://localhost:1337/api/users/logout HTTP/1.1
content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVGVzdFVzZXIyIiwiaWQiOjcsImlhdCI6MTU4MjY2ODYwNX0.WJkoO93q-vSsT5gzOTXLjI48ASwBvolE--FxoNSJqKk"
}

###

POST http://localhost:1337/api/users/refresh HTTP/1.1
content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVGVzdFVzZXIyIiwiaWQiOjcsImlhdCI6MTU4MjY2ODY1M30.wPMWvCQXsMqDQTAJ016RHq8SzUW0evDtba_4nWdkDa4"
}

###