POST http://localhost:1337/api/users/register/ HTTP/1.1
content-type: application/json

{
    "userName": "TESTDUP",
    "email": "TEST@provider.com",
    "password": "P@ssw0rd",
    "firstName": "FirstName",
    "lastName": "LastName"
}

###

POST http://localhost:1337/api/users/login HTTP/1.1
content-type: application/json

{
    "userName": "admin",
    "password": "admin"
}

###

//LOGOUT via AcessToken
DELETE http://localhost:1337/api/users/logout HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSkVTVFVzZXIxIiwiaWQiOjE2MiwiaWF0IjoxNTgzNTk1NDM3LCJleHAiOjE2MTUxMzE0Mzd9.GeaOr2U6YgZW-ChXD_VLjEkxhyj6Sm4YRqai2KK6nHM

###

//LOGOUT via RefreshToken
DELETE http://localhost:1337/api/users/logout HTTP/1.1
content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVEVTVERVUCIsImlkIjo3NywiaWF0IjoxNTgzNTI5MTk2fQ.XHNT5Ivn_UiUwlop_TyAP_ujioar5tT0nC4cFDT_PbQ"
}

###

POST http://localhost:1337/api/users/refresh HTTP/1.1
content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVEVTVERVUCIsImlkIjo3NywiaWF0IjoxNTgzNTMwMzUwfQ.CxU-zhVI_CA8t-JXou_CB-75Ag57kUwsKc6_-sKPwko"
}

###