module.exports = {

  friendlyName: 'Refresh Access Token',

  description: 'Sends a new Access Token',

  inputs: {
    token: {
      description: 'Active JWT Refresh Token.',
      type: 'string'
    }
  },

  exits: {
    success: {
      responseType: '',
      statusCode: 200
    },
    missingParams: {
      description: 'Missing parameters',
      statusCode: 400
    },
    invalidToken: {
      description: 'Invalid Token',
      statusCode: 403
    }
  },

  fn: async function(inputs, exits) {
    const jwt = require('jsonwebtoken');
    if(!inputs.token) {
      return exits.missingParams();
    }
    var user = await sails.helpers.authenticateRefreshToken(inputs.token);
    if(!user) {
      return exits.invalidToken();
    }

    delete user['iat']; // Remove autogenerated attribute "initiated at"
    delete user['exp']; // Remove autogenerated attribute "expires at"

    const accessToken = jwt.sign(user, sails.config.jwts.ACCESS_TOKEN_SECRET,
      { expiresIn: sails.config.jwts.EXPIRATION_TIME });
    return exits.success({accessToken: accessToken, expiresIn: sails.config.jwts.EXPIRATION_TIME});
  }
};
